import { DM_Sans, Baloo_Bhaijaan_2 } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import StateProvider from "@/providers/StateProvider";

const dmSans = DM_Sans({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-dmSans",
});
const baloo = Baloo_Bhaijaan_2({
    subsets: ["latin"],
    weight: ["600", "700"],
    variable: "--font-baloo",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${dmSans.variable} ${baloo.variable}`}>
                <div className="min-w-full min-h-screen bg-[#eeeff0]">
                    <Navbar />
                    <StateProvider>{children}</StateProvider>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
